server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3308/ecommerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ecommerce
    password: ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 'asdklfasljdghjldcnkljavnjkfdncvkjbwaekjfbasjhbvkjbaxkjcbhvkljawebfkjbcahvbkaerbwkjbaksjxckjvnadxccvkasdkjvbawekhbkahwebvxcnvksda'
