server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3308/ecommerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ecommerce
    password: ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventoryGroup
      # byte -> Java로 역직렬화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka